version: '4'
services:
  keycloak-mysql:
    container_name: keycloak-mysql
    image: mysql:8.3.0
    volumes:
      - ../docker_db/mysql_keycloak/:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: keycloak
      MYSQL_USER: keycloak_user
      MYSQL_PASSWORD: keycloak_password

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:25.0.1
    command: [ "start-dev", "--import-realm" ]
    environment:
      DB_VENDOR: MYSQL
      DB_ADDR: mysql
      DB_DATABASE: keycloak
      DB_USER: keycloak_user
      DB_PASSWORD: keycloak_password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8090:8080"
    volumes:
      - ../docker_db/keycloak/realms/:/opt/keycloak/data/import/
    depends_on:
      - keycloak-mysql