
spring.application.name=NOTIFICATION-SERVICE

server.port=8093

# Mail Properties
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=fuwood90@gmail.com
# new third party app password generated for gmail my-notification-service :: PASSWORD
spring.mail.password=qhuidcuelaayylac
#spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
# below property is assuring for secured connection
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.writetimeout=10000
spring.mail.properties.mail.smtp.connectiontimeout=10000
spring.mail.properties.mail.smtp.timeout=10000

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=10MB

# Set the logging level for a specific package or class
logging.level.com.mylearning=INFO

# Kafka Config
# if more than one kafka servers are running then we can configure like this with , to list all kafka servers
# spring.kafka.consumer.bootstrap-servers=localhost:9092,localhost:9094
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.auto-offset-reset=earliest
# When you set up a Kafka consumer, you can make multiple instances of a Microservice work as a team to handle messages from a Kafka topic.
# This team is what Kafka calls a consumer group. Each consumer in the group reads messages from the topic, ensuring that, together, they process messages faster.
# distributing the messages among the consumers in the group.
spring.kafka.consumer.group-id=notificationService
# This property specifies the deserializer class for the keys of Kafka records.Kafka needs to deserialize the key (if present) from its binary representation (usually a byte array) into a usable format (e.g., a String or custom Java object)
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
# this property specifies the deserializer class for the values of Kafka records. It determines how the actual message content (payload) is deserialized
# ErrorHandlingDeserializer wraps another delegate deserializer and handles deserialization errors gracefully.
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
# if we are not using AVRO Schema for Serialization and Deserialization
#spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer

#  property sets the delegate deserializer class for keys which means in our case that the actual deserialization of keys (after error handling) will be done using this class.
spring.kafka.consumer.properties.spring.deserializer.key.delegate.class=org.apache.kafka.common.serialization.StringDeserializer
# this property specifies the delegate deserializer class for values. This means that after error handling, the actual deserialization of values will be performed using the Avro-specific deserializer.
spring.kafka.consumer.properties.spring.deserializer.value.delegate.class=io.confluent.kafka.serializers.KafkaAvroDeserializer
spring.kafka.consumer.properties.schema.registry.url=http://localhost:8091
# property is used in Spring Kafka to configure the Avro-specific deserializer for Kafka consumers. enables the use of Avro?s specific record classes for deserialization.
spring.kafka.consumer.properties.specific.avro.reader=true

# This configuration property is quite important for security when you?re deserializing JSON messages in your Kafka consumer.
# It specifies which Java packages are ?trusted? for JSON deserialization by your application.
# this means that only the classes in the com.mylearning.event package can be deserialized.
# You can also specify multiple packages by separating them with commas.
# we can use below property when consumer throws error in Kafka application for IllegalArgumentException due to class is not in Trusted Packages
#spring.kafka.consumer.properties.spring.json.trusted.packages=com.mylearning.event

# Caused by: java.lang.IllegalArgumentException: The class 'event.com.mylearning.OrderPlacedEvent'
# is not in the trusted packages: [java.util, java.lang, com.mylearning.notificationservice.event, com.mylearning.notificationservice.event.*].
# If you believe this class is safe to deserialize, please provide its name. If the serialization is only done by a trusted source, you can also enable trust all (*).
# we have to provide json type mapping explicitly we have to provide reference to the class we have to know to deserialize the OrderPlacedEvent object.
# and we have to provide this class for mapping to deserialize should be following the same package level or path of package as same as it is in the Order-Service
#spring.kafka.consumer.properties.spring.json.type.mapping=event:com.mylearning.event.OrderPlacedEvent

# token value as some random value here :: as event and we have fully-qualified class name of the OrderPlacedEvent
# This property is important to add about mapping type .here trying to serialize the orderPlacedEvent and in notification-service whenever we receive this information from order-service
# we have to provide mapping type on site in the producer side and also consumer side
# on the producer side we will define what exactly is the type which we are sending for OrderPlacedEvent and on consumer side
# we will also define what is the exact type we are expecting . Here we are providing json type mapping as part of this json type mapping
# we are providing token value followed by the fully qualified class name of the body we are sending as part of the message
# the token value i have provided as some random value as event and followed by the fully qualified class name of the OrderPlacedEvent
# this way springboot will understand what is the json type mapping of the OrderPlacedEvent so we have to define the similar property at consumer side too.
# HERE TOKEN VALUE i.e. "event"  MUST BE SAME AT BOTH CONSUMER AND PRODUCER SIDE
#spring.kafka.consumer.properties.spring.json.type.mapping=event:com.mylearning.event.OrderPlacedEvent


# Actuator Endpoints
# After adding the properties run application and open the URL ? http://localhost:8086/actuator/prometheus to see different metrics that are exposed by the micrometer.
# this property exposes the endpoints health, info, metrics, and prometheus through the actuator.
management.endpoints.web.exposure.include=health, info, metrics, prometheus
# this is the internal property of prometheus we need to add this as true
# this property  is used by the micrometer to gather the metrics in the form of a histogram and send it to Prometheus.
management.metrics.distribution.percentiles-histogram.http.server.requests=true
management.observations.key-values.application=NOTIFICATION-SERVICE

# enables the export of metrics to Prometheus.
management.prometheus.metrics.export.enabled=true
# This property enables the Prometheus endpoint in your application. With this property enabled, you can access the Prometheus metrics endpoint at http://localhost:8086/actuator/prometheus
management.endpoint.prometheus.enabled=true


# this property is mandatory
# Micrometer Tracing will only send 10% of the traces it generates to Tempo, just to avoid overwhelming it with a lot of requests.
# We can set it to 100% by adding the below property to our application.yml file
# By default springboot will generate traces for only 10% of the requests
# by setting it to 1.0 we are setting so that it will generate 100% traces of all the requests which is processed by the application
management.tracing.sampling.probability=1.0