spring.application.name=NOTIFICATION-SERVICE

spring.profiles.active=dev

# Mail Properties
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=ce353d37d014ce
spring.mail.password=87d015cdf1d3d3
spring.mail.protocol=smtp