spring.application.name=NOTIFICATION-SERVICE

spring.profiles.active=gmail

# Mail Properties
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=USERNAME
spring.mail.password=PASSWORD
spring.mail.protocol=smtp
