
spring.application.name=API-Gateway

server.port=8089


# configure the Authorization Server details inside our Spring Boot API Gateway application.
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8090/realms/spring-microservices-realm


# Aggregating the documentation in API Gateway :: below properties to aggregate the URLs of all the 3 services.
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true
springdoc.swagger-ui.urls[0].name=Product Service
springdoc.swagger-ui.urls[0].url=/aggregate/product-service/v3/api-docs
springdoc.swagger-ui.urls[1].name=Order Service
springdoc.swagger-ui.urls[1].url=/aggregate/order-service/v3/api-docs
springdoc.swagger-ui.urls[2].name=Inventory Service
springdoc.swagger-ui.urls[2].url=/aggregate/inventory-service/v3/api-docs


#Resilinece4j Properties
resilience4j.circuitbreaker.configs.default.registerHealthIndicator=true
resilience4j.circuitbreaker.configs.default.slidingWindowType=COUNT_BASED
resilience4j.circuitbreaker.configs.default.slidingWindowSize=10
resilience4j.circuitbreaker.configs.default.failureRateThreshold=50
resilience4j.circuitbreaker.configs.default.waitDurationInOpenState=5s
resilience4j.circuitbreaker.configs.default.permittedNumberOfCallsInHalfOpenState=3
resilience4j.circuitbreaker.configs.default.automaticTransitionFromOpenToHalfOpenEnabled=true
resilience4j.circuitbreaker.configs.default.minimum-number-of-calls=5

# Enable Circuit Breaker for Timeouts
# With this configuration, the circuit breaker will be OPEN, when the remote service is taking more than 3 seconds to send back the response.
resilience4j.timelimiter.configs.default.timeout-duration=3s

# Resilience4J Retry Properties
# Sometimes, the service can be unavailable due to a small network issue (or) any other minor issue, in those cases,
# it?s better to retry the call instead of directly activating the Circuit Breaker.
# configuration will retry for a maximum of 3 times, with a wait of 5 seconds in between the retries.
resilience4j.retry.configs.default.max-attempts=3
resilience4j.retry.configs.default.wait-duration=5s

