version: '4'
services:
  mongodb:
    image: mysql:8.3.0
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: raj123
      MYSQL_USER: raj
      MYSQL_PASSWORD: raj123
      MYSQL_DATABASE: order_service
    volumes:
      - ./mysql:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql