spring.application.name=PRODUCT-SERVICE

server.port=8086

spring.data.mongodb.database=product-service
spring.data.mongodb.port=27017
spring.data.mongodb.host=localhost
spring.data.mongodb.username=raj
spring.data.mongodb.password=raj123
#spring.data.mongodb.auto-index-creation=true
spring.data.mongodb.authentication-database=admin

#spring.data.mongodb.uri=mongodb://raj:raj123@localhost:27017/product-service?authSource=admin



# The Swagger UI page will then be available at http://server:port/context-path/swagger-ui.html and
# the OpenAPI description will be available at the following url
# for json format: http://server:port/context-path/v3/api-docs
#http://server:port/context-path/v3/api-docs
#server: The server name or IP
#port: The server port
#context-path: The context path of the application


# by default, spring doc open API exposes the documentation at URL path ? /swagger-ui/index.html
# swagger-ui custom path
# http://localhost:8086/swagger-ui.html gives the documentation at URL path
springdoc.swagger-ui.path=/swagger-ui.html
# Disabling the swagger-ui
springdoc.swagger-ui.enabled=true



# /api-docs endpoint custom path
#  http://localhost:8086/api-docs :: gives the documentation as REST API in JSON format
springdoc.api-docs.path=/api-docs
# Disabling the /v3/api-docs endpoint
springdoc.api-docs.enabled=true

springdoc.packages-to-scan=com.mylearning.productservice
springdoc.swagger-ui.tryItOutEnabled=true
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.filter=true

product.openapi.dev-url=http://localhost:8086
#codebuffer.openapi.prod-url=https://bezkoder-api.com


# Actuator Endpoints
# After adding the properties run application and open the URL ? http://localhost:8086/actuator/prometheus to see different metrics that are exposed by the micrometer.
# this property exposes the endpoints health, info, metrics, and prometheus through the actuator.
# For metrics endpoint is exposed http://localhost:8086/actuator/metrics. For Prometheus, it will be available at http://localhost:8086/actuator/prometheus.
management.endpoints.web.exposure.include=health, info, metrics, prometheus
# this is the internal property of prometheus we need to add this as true
# this property  is used by the micrometer to gather the metrics in the form of a histogram and send it to Prometheus.
# By setting this property to true, you enable the collection of detailed metrics on the distribution of HTTP request latencies, which can help in analyzing the performance and identifying potential bottlenecks.
management.metrics.distribution.percentiles-histogram.http.server.requests=true
# management.observations.key-values.application property sets a custom key-value pair for the application.application is the key, and PRODUCT-SERVICE is the value
# useful for tagging all your metrics with a specific identifier, making it easier to filter and search for metrics related to the PRODUCT-SERVICE application in your monitoring system
management.observations.key-values.application=PRODUCT-SERVICE
# enables the export of metrics to Prometheus.
management.prometheus.metrics.export.enabled=true
# This property enables the Prometheus endpoint in your application. With this property enabled, you can access the Prometheus metrics endpoint at http://localhost:8086/actuator/prometheus
management.endpoint.prometheus.enabled=true


# this property is mandatory
# Micrometer Tracing will only send 10% of the traces it generates to Tempo, just to avoid overwhelming it with a lot of requests.
# We can set it to 100% by adding the below property to our application.yml file
# By default springboot will generate traces for only 10% of the requests
# by setting it to 1.0 we are setting so that it will generate 100% traces of all the requests which is processed by the application
# if the value is set to 0 then no requests will be sampled and 1 means all requests will be sampled means all the requests will be sampled
# by default SpringBoot set this property to 0.1 which means only 10% of requests will be sampled.
management.tracing.sampling.probability=1.0

